//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Data.DTCInstructor
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DtcInstructorEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DtcInstructorEntities object using the connection string found in the 'DtcInstructorEntities' section of the application configuration file.
        /// </summary>
        public DtcInstructorEntities() : base("name=DtcInstructorEntities", "DtcInstructorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DtcInstructorEntities object.
        /// </summary>
        public DtcInstructorEntities(string connectionString) : base(connectionString, "DtcInstructorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DtcInstructorEntities object.
        /// </summary>
        public DtcInstructorEntities(EntityConnection connection) : base(connection, "DtcInstructorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OutgoingPledgeOrder> OutgoingPledgeOrders
        {
            get
            {
                if ((_OutgoingPledgeOrders == null))
                {
                    _OutgoingPledgeOrders = base.CreateObjectSet<OutgoingPledgeOrder>("OutgoingPledgeOrders");
                }
                return _OutgoingPledgeOrders;
            }
        }
        private ObjectSet<OutgoingPledgeOrder> _OutgoingPledgeOrders;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OutgoingPledgeOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOutgoingPledgeOrders(OutgoingPledgeOrder outgoingPledgeOrder)
        {
            base.AddObject("OutgoingPledgeOrders", outgoingPledgeOrder);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DtcInstructorModel", Name="OutgoingPledgeOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OutgoingPledgeOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OutgoingPledgeOrder object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateEntered">Initial value of the DateEntered property.</param>
        /// <param name="enteredBy">Initial value of the EnteredBy property.</param>
        /// <param name="feedbackIndicator">Initial value of the FeedbackIndicator property.</param>
        /// <param name="productionIndicator">Initial value of the ProductionIndicator property.</param>
        /// <param name="recType">Initial value of the RecType property.</param>
        /// <param name="recordSuffix">Initial value of the RecordSuffix property.</param>
        /// <param name="versionNumber">Initial value of the VersionNumber property.</param>
        /// <param name="userReferenceNumber">Initial value of the UserReferenceNumber property.</param>
        /// <param name="adressee">Initial value of the Adressee property.</param>
        /// <param name="recordType">Initial value of the RecordType property.</param>
        /// <param name="pledgor">Initial value of the Pledgor property.</param>
        /// <param name="pledgee">Initial value of the Pledgee property.</param>
        /// <param name="cusip">Initial value of the Cusip property.</param>
        /// <param name="shareQuantity">Initial value of the ShareQuantity property.</param>
        /// <param name="loanDate">Initial value of the LoanDate property.</param>
        /// <param name="loanValueWhole">Initial value of the LoanValueWhole property.</param>
        /// <param name="loanValueDecimal">Initial value of the LoanValueDecimal property.</param>
        /// <param name="pledgePurpose">Initial value of the PledgePurpose property.</param>
        /// <param name="releaseType">Initial value of the ReleaseType property.</param>
        /// <param name="hypothecationCode">Initial value of the HypothecationCode property.</param>
        /// <param name="preventPendIndicator">Initial value of the PreventPendIndicator property.</param>
        /// <param name="cnsIndicator">Initial value of the CnsIndicator property.</param>
        /// <param name="ipoIndicator">Initial value of the IpoIndicator property.</param>
        /// <param name="ptaIndicator">Initial value of the PtaIndicator property.</param>
        /// <param name="federalReservePurpose">Initial value of the FederalReservePurpose property.</param>
        /// <param name="occParticipantNumber">Initial value of the OccParticipantNumber property.</param>
        /// <param name="bankAbaNumber">Initial value of the BankAbaNumber property.</param>
        /// <param name="occNumber">Initial value of the OccNumber property.</param>
        /// <param name="occClearingGroupId">Initial value of the OccClearingGroupId property.</param>
        /// <param name="occClearingMemberNumber">Initial value of the OccClearingMemberNumber property.</param>
        /// <param name="occAccountType">Initial value of the OccAccountType property.</param>
        /// <param name="occAccountId">Initial value of the OccAccountId property.</param>
        /// <param name="occCollateralType">Initial value of the OccCollateralType property.</param>
        /// <param name="occOptionSymbol">Initial value of the OccOptionSymbol property.</param>
        /// <param name="occExpirationYear">Initial value of the OccExpirationYear property.</param>
        /// <param name="occExpirationMonth">Initial value of the OccExpirationMonth property.</param>
        /// <param name="occExpirationDay">Initial value of the OccExpirationDay property.</param>
        /// <param name="occOptionType">Initial value of the OccOptionType property.</param>
        /// <param name="occOptionStrike">Initial value of the OccOptionStrike property.</param>
        /// <param name="occOptionStrikeDecimal">Initial value of the OccOptionStrikeDecimal property.</param>
        /// <param name="blank">Initial value of the Blank property.</param>
        /// <param name="crossReferenceNumber">Initial value of the CrossReferenceNumber property.</param>
        /// <param name="customerAccountNumber">Initial value of the CustomerAccountNumber property.</param>
        /// <param name="occFiller">Initial value of the OccFiller property.</param>
        /// <param name="dtccFiller">Initial value of the DtccFiller property.</param>
        public static OutgoingPledgeOrder CreateOutgoingPledgeOrder(global::System.Int32 id, global::System.DateTime dateEntered, global::System.String enteredBy, global::System.String feedbackIndicator, global::System.String productionIndicator, global::System.String recType, global::System.String recordSuffix, global::System.String versionNumber, global::System.String userReferenceNumber, global::System.String adressee, global::System.String recordType, global::System.String pledgor, global::System.String pledgee, global::System.String cusip, global::System.String shareQuantity, global::System.String loanDate, global::System.String loanValueWhole, global::System.String loanValueDecimal, global::System.String pledgePurpose, global::System.String releaseType, global::System.String hypothecationCode, global::System.String preventPendIndicator, global::System.String cnsIndicator, global::System.String ipoIndicator, global::System.String ptaIndicator, global::System.String federalReservePurpose, global::System.String occParticipantNumber, global::System.String bankAbaNumber, global::System.String occNumber, global::System.String occClearingGroupId, global::System.String occClearingMemberNumber, global::System.String occAccountType, global::System.String occAccountId, global::System.String occCollateralType, global::System.String occOptionSymbol, global::System.String occExpirationYear, global::System.String occExpirationMonth, global::System.String occExpirationDay, global::System.String occOptionType, global::System.String occOptionStrike, global::System.String occOptionStrikeDecimal, global::System.String blank, global::System.String crossReferenceNumber, global::System.String customerAccountNumber, global::System.String occFiller, global::System.String dtccFiller)
        {
            OutgoingPledgeOrder outgoingPledgeOrder = new OutgoingPledgeOrder();
            outgoingPledgeOrder.Id = id;
            outgoingPledgeOrder.DateEntered = dateEntered;
            outgoingPledgeOrder.EnteredBy = enteredBy;
            outgoingPledgeOrder.FeedbackIndicator = feedbackIndicator;
            outgoingPledgeOrder.ProductionIndicator = productionIndicator;
            outgoingPledgeOrder.RecType = recType;
            outgoingPledgeOrder.RecordSuffix = recordSuffix;
            outgoingPledgeOrder.VersionNumber = versionNumber;
            outgoingPledgeOrder.UserReferenceNumber = userReferenceNumber;
            outgoingPledgeOrder.Adressee = adressee;
            outgoingPledgeOrder.RecordType = recordType;
            outgoingPledgeOrder.Pledgor = pledgor;
            outgoingPledgeOrder.Pledgee = pledgee;
            outgoingPledgeOrder.Cusip = cusip;
            outgoingPledgeOrder.ShareQuantity = shareQuantity;
            outgoingPledgeOrder.LoanDate = loanDate;
            outgoingPledgeOrder.LoanValueWhole = loanValueWhole;
            outgoingPledgeOrder.LoanValueDecimal = loanValueDecimal;
            outgoingPledgeOrder.PledgePurpose = pledgePurpose;
            outgoingPledgeOrder.ReleaseType = releaseType;
            outgoingPledgeOrder.HypothecationCode = hypothecationCode;
            outgoingPledgeOrder.PreventPendIndicator = preventPendIndicator;
            outgoingPledgeOrder.CnsIndicator = cnsIndicator;
            outgoingPledgeOrder.IpoIndicator = ipoIndicator;
            outgoingPledgeOrder.PtaIndicator = ptaIndicator;
            outgoingPledgeOrder.FederalReservePurpose = federalReservePurpose;
            outgoingPledgeOrder.OccParticipantNumber = occParticipantNumber;
            outgoingPledgeOrder.BankAbaNumber = bankAbaNumber;
            outgoingPledgeOrder.OccNumber = occNumber;
            outgoingPledgeOrder.OccClearingGroupId = occClearingGroupId;
            outgoingPledgeOrder.OccClearingMemberNumber = occClearingMemberNumber;
            outgoingPledgeOrder.OccAccountType = occAccountType;
            outgoingPledgeOrder.OccAccountId = occAccountId;
            outgoingPledgeOrder.OccCollateralType = occCollateralType;
            outgoingPledgeOrder.OccOptionSymbol = occOptionSymbol;
            outgoingPledgeOrder.OccExpirationYear = occExpirationYear;
            outgoingPledgeOrder.OccExpirationMonth = occExpirationMonth;
            outgoingPledgeOrder.OccExpirationDay = occExpirationDay;
            outgoingPledgeOrder.OccOptionType = occOptionType;
            outgoingPledgeOrder.OccOptionStrike = occOptionStrike;
            outgoingPledgeOrder.OccOptionStrikeDecimal = occOptionStrikeDecimal;
            outgoingPledgeOrder.Blank = blank;
            outgoingPledgeOrder.CrossReferenceNumber = crossReferenceNumber;
            outgoingPledgeOrder.CustomerAccountNumber = customerAccountNumber;
            outgoingPledgeOrder.OccFiller = occFiller;
            outgoingPledgeOrder.DtccFiller = dtccFiller;
            return outgoingPledgeOrder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageId
        {
            get
            {
                return _MessageId;
            }
            set
            {
                OnMessageIdChanging(value);
                ReportPropertyChanging("MessageId");
                _MessageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageId");
                OnMessageIdChanged();
            }
        }
        private global::System.String _MessageId;
        partial void OnMessageIdChanging(global::System.String value);
        partial void OnMessageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateEntered
        {
            get
            {
                return _DateEntered;
            }
            set
            {
                OnDateEnteredChanging(value);
                ReportPropertyChanging("DateEntered");
                _DateEntered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateEntered");
                OnDateEnteredChanged();
            }
        }
        private global::System.DateTime _DateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime value);
        partial void OnDateEnteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnteredBy
        {
            get
            {
                return _EnteredBy;
            }
            set
            {
                OnEnteredByChanging(value);
                ReportPropertyChanging("EnteredBy");
                _EnteredBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnteredBy");
                OnEnteredByChanged();
            }
        }
        private global::System.String _EnteredBy;
        partial void OnEnteredByChanging(global::System.String value);
        partial void OnEnteredByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSent
        {
            get
            {
                return _DateSent;
            }
            set
            {
                OnDateSentChanging(value);
                ReportPropertyChanging("DateSent");
                _DateSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSent");
                OnDateSentChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSent;
        partial void OnDateSentChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateConfirmed
        {
            get
            {
                return _DateConfirmed;
            }
            set
            {
                OnDateConfirmedChanging(value);
                ReportPropertyChanging("DateConfirmed");
                _DateConfirmed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateConfirmed");
                OnDateConfirmedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateConfirmed;
        partial void OnDateConfirmedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateConfirmedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FeedbackIndicator
        {
            get
            {
                return _FeedbackIndicator;
            }
            set
            {
                OnFeedbackIndicatorChanging(value);
                ReportPropertyChanging("FeedbackIndicator");
                _FeedbackIndicator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FeedbackIndicator");
                OnFeedbackIndicatorChanged();
            }
        }
        private global::System.String _FeedbackIndicator;
        partial void OnFeedbackIndicatorChanging(global::System.String value);
        partial void OnFeedbackIndicatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductionIndicator
        {
            get
            {
                return _ProductionIndicator;
            }
            set
            {
                OnProductionIndicatorChanging(value);
                ReportPropertyChanging("ProductionIndicator");
                _ProductionIndicator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductionIndicator");
                OnProductionIndicatorChanged();
            }
        }
        private global::System.String _ProductionIndicator;
        partial void OnProductionIndicatorChanging(global::System.String value);
        partial void OnProductionIndicatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecType
        {
            get
            {
                return _RecType;
            }
            set
            {
                OnRecTypeChanging(value);
                ReportPropertyChanging("RecType");
                _RecType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecType");
                OnRecTypeChanged();
            }
        }
        private global::System.String _RecType;
        partial void OnRecTypeChanging(global::System.String value);
        partial void OnRecTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecordSuffix
        {
            get
            {
                return _RecordSuffix;
            }
            set
            {
                OnRecordSuffixChanging(value);
                ReportPropertyChanging("RecordSuffix");
                _RecordSuffix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecordSuffix");
                OnRecordSuffixChanged();
            }
        }
        private global::System.String _RecordSuffix;
        partial void OnRecordSuffixChanging(global::System.String value);
        partial void OnRecordSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VersionNumber
        {
            get
            {
                return _VersionNumber;
            }
            set
            {
                OnVersionNumberChanging(value);
                ReportPropertyChanging("VersionNumber");
                _VersionNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VersionNumber");
                OnVersionNumberChanged();
            }
        }
        private global::System.String _VersionNumber;
        partial void OnVersionNumberChanging(global::System.String value);
        partial void OnVersionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserReferenceNumber
        {
            get
            {
                return _UserReferenceNumber;
            }
            set
            {
                OnUserReferenceNumberChanging(value);
                ReportPropertyChanging("UserReferenceNumber");
                _UserReferenceNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserReferenceNumber");
                OnUserReferenceNumberChanged();
            }
        }
        private global::System.String _UserReferenceNumber;
        partial void OnUserReferenceNumberChanging(global::System.String value);
        partial void OnUserReferenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adressee
        {
            get
            {
                return _Adressee;
            }
            set
            {
                OnAdresseeChanging(value);
                ReportPropertyChanging("Adressee");
                _Adressee = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adressee");
                OnAdresseeChanged();
            }
        }
        private global::System.String _Adressee;
        partial void OnAdresseeChanging(global::System.String value);
        partial void OnAdresseeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecordType
        {
            get
            {
                return _RecordType;
            }
            set
            {
                OnRecordTypeChanging(value);
                ReportPropertyChanging("RecordType");
                _RecordType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecordType");
                OnRecordTypeChanged();
            }
        }
        private global::System.String _RecordType;
        partial void OnRecordTypeChanging(global::System.String value);
        partial void OnRecordTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pledgor
        {
            get
            {
                return _Pledgor;
            }
            set
            {
                OnPledgorChanging(value);
                ReportPropertyChanging("Pledgor");
                _Pledgor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pledgor");
                OnPledgorChanged();
            }
        }
        private global::System.String _Pledgor;
        partial void OnPledgorChanging(global::System.String value);
        partial void OnPledgorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pledgee
        {
            get
            {
                return _Pledgee;
            }
            set
            {
                OnPledgeeChanging(value);
                ReportPropertyChanging("Pledgee");
                _Pledgee = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pledgee");
                OnPledgeeChanged();
            }
        }
        private global::System.String _Pledgee;
        partial void OnPledgeeChanging(global::System.String value);
        partial void OnPledgeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cusip
        {
            get
            {
                return _Cusip;
            }
            set
            {
                OnCusipChanging(value);
                ReportPropertyChanging("Cusip");
                _Cusip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cusip");
                OnCusipChanged();
            }
        }
        private global::System.String _Cusip;
        partial void OnCusipChanging(global::System.String value);
        partial void OnCusipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShareQuantity
        {
            get
            {
                return _ShareQuantity;
            }
            set
            {
                OnShareQuantityChanging(value);
                ReportPropertyChanging("ShareQuantity");
                _ShareQuantity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShareQuantity");
                OnShareQuantityChanged();
            }
        }
        private global::System.String _ShareQuantity;
        partial void OnShareQuantityChanging(global::System.String value);
        partial void OnShareQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoanDate
        {
            get
            {
                return _LoanDate;
            }
            set
            {
                OnLoanDateChanging(value);
                ReportPropertyChanging("LoanDate");
                _LoanDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoanDate");
                OnLoanDateChanged();
            }
        }
        private global::System.String _LoanDate;
        partial void OnLoanDateChanging(global::System.String value);
        partial void OnLoanDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoanValueWhole
        {
            get
            {
                return _LoanValueWhole;
            }
            set
            {
                OnLoanValueWholeChanging(value);
                ReportPropertyChanging("LoanValueWhole");
                _LoanValueWhole = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoanValueWhole");
                OnLoanValueWholeChanged();
            }
        }
        private global::System.String _LoanValueWhole;
        partial void OnLoanValueWholeChanging(global::System.String value);
        partial void OnLoanValueWholeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoanValueDecimal
        {
            get
            {
                return _LoanValueDecimal;
            }
            set
            {
                OnLoanValueDecimalChanging(value);
                ReportPropertyChanging("LoanValueDecimal");
                _LoanValueDecimal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoanValueDecimal");
                OnLoanValueDecimalChanged();
            }
        }
        private global::System.String _LoanValueDecimal;
        partial void OnLoanValueDecimalChanging(global::System.String value);
        partial void OnLoanValueDecimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PledgePurpose
        {
            get
            {
                return _PledgePurpose;
            }
            set
            {
                OnPledgePurposeChanging(value);
                ReportPropertyChanging("PledgePurpose");
                _PledgePurpose = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PledgePurpose");
                OnPledgePurposeChanged();
            }
        }
        private global::System.String _PledgePurpose;
        partial void OnPledgePurposeChanging(global::System.String value);
        partial void OnPledgePurposeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReleaseType
        {
            get
            {
                return _ReleaseType;
            }
            set
            {
                OnReleaseTypeChanging(value);
                ReportPropertyChanging("ReleaseType");
                _ReleaseType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReleaseType");
                OnReleaseTypeChanged();
            }
        }
        private global::System.String _ReleaseType;
        partial void OnReleaseTypeChanging(global::System.String value);
        partial void OnReleaseTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HypothecationCode
        {
            get
            {
                return _HypothecationCode;
            }
            set
            {
                OnHypothecationCodeChanging(value);
                ReportPropertyChanging("HypothecationCode");
                _HypothecationCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HypothecationCode");
                OnHypothecationCodeChanged();
            }
        }
        private global::System.String _HypothecationCode;
        partial void OnHypothecationCodeChanging(global::System.String value);
        partial void OnHypothecationCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PreventPendIndicator
        {
            get
            {
                return _PreventPendIndicator;
            }
            set
            {
                OnPreventPendIndicatorChanging(value);
                ReportPropertyChanging("PreventPendIndicator");
                _PreventPendIndicator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PreventPendIndicator");
                OnPreventPendIndicatorChanged();
            }
        }
        private global::System.String _PreventPendIndicator;
        partial void OnPreventPendIndicatorChanging(global::System.String value);
        partial void OnPreventPendIndicatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CnsIndicator
        {
            get
            {
                return _CnsIndicator;
            }
            set
            {
                OnCnsIndicatorChanging(value);
                ReportPropertyChanging("CnsIndicator");
                _CnsIndicator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CnsIndicator");
                OnCnsIndicatorChanged();
            }
        }
        private global::System.String _CnsIndicator;
        partial void OnCnsIndicatorChanging(global::System.String value);
        partial void OnCnsIndicatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IpoIndicator
        {
            get
            {
                return _IpoIndicator;
            }
            set
            {
                OnIpoIndicatorChanging(value);
                ReportPropertyChanging("IpoIndicator");
                _IpoIndicator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IpoIndicator");
                OnIpoIndicatorChanged();
            }
        }
        private global::System.String _IpoIndicator;
        partial void OnIpoIndicatorChanging(global::System.String value);
        partial void OnIpoIndicatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PtaIndicator
        {
            get
            {
                return _PtaIndicator;
            }
            set
            {
                OnPtaIndicatorChanging(value);
                ReportPropertyChanging("PtaIndicator");
                _PtaIndicator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PtaIndicator");
                OnPtaIndicatorChanged();
            }
        }
        private global::System.String _PtaIndicator;
        partial void OnPtaIndicatorChanging(global::System.String value);
        partial void OnPtaIndicatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FederalReservePurpose
        {
            get
            {
                return _FederalReservePurpose;
            }
            set
            {
                OnFederalReservePurposeChanging(value);
                ReportPropertyChanging("FederalReservePurpose");
                _FederalReservePurpose = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FederalReservePurpose");
                OnFederalReservePurposeChanged();
            }
        }
        private global::System.String _FederalReservePurpose;
        partial void OnFederalReservePurposeChanging(global::System.String value);
        partial void OnFederalReservePurposeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccParticipantNumber
        {
            get
            {
                return _OccParticipantNumber;
            }
            set
            {
                OnOccParticipantNumberChanging(value);
                ReportPropertyChanging("OccParticipantNumber");
                _OccParticipantNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccParticipantNumber");
                OnOccParticipantNumberChanged();
            }
        }
        private global::System.String _OccParticipantNumber;
        partial void OnOccParticipantNumberChanging(global::System.String value);
        partial void OnOccParticipantNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BankAbaNumber
        {
            get
            {
                return _BankAbaNumber;
            }
            set
            {
                OnBankAbaNumberChanging(value);
                ReportPropertyChanging("BankAbaNumber");
                _BankAbaNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BankAbaNumber");
                OnBankAbaNumberChanged();
            }
        }
        private global::System.String _BankAbaNumber;
        partial void OnBankAbaNumberChanging(global::System.String value);
        partial void OnBankAbaNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccNumber
        {
            get
            {
                return _OccNumber;
            }
            set
            {
                OnOccNumberChanging(value);
                ReportPropertyChanging("OccNumber");
                _OccNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccNumber");
                OnOccNumberChanged();
            }
        }
        private global::System.String _OccNumber;
        partial void OnOccNumberChanging(global::System.String value);
        partial void OnOccNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccClearingGroupId
        {
            get
            {
                return _OccClearingGroupId;
            }
            set
            {
                OnOccClearingGroupIdChanging(value);
                ReportPropertyChanging("OccClearingGroupId");
                _OccClearingGroupId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccClearingGroupId");
                OnOccClearingGroupIdChanged();
            }
        }
        private global::System.String _OccClearingGroupId;
        partial void OnOccClearingGroupIdChanging(global::System.String value);
        partial void OnOccClearingGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccClearingMemberNumber
        {
            get
            {
                return _OccClearingMemberNumber;
            }
            set
            {
                OnOccClearingMemberNumberChanging(value);
                ReportPropertyChanging("OccClearingMemberNumber");
                _OccClearingMemberNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccClearingMemberNumber");
                OnOccClearingMemberNumberChanged();
            }
        }
        private global::System.String _OccClearingMemberNumber;
        partial void OnOccClearingMemberNumberChanging(global::System.String value);
        partial void OnOccClearingMemberNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccAccountType
        {
            get
            {
                return _OccAccountType;
            }
            set
            {
                OnOccAccountTypeChanging(value);
                ReportPropertyChanging("OccAccountType");
                _OccAccountType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccAccountType");
                OnOccAccountTypeChanged();
            }
        }
        private global::System.String _OccAccountType;
        partial void OnOccAccountTypeChanging(global::System.String value);
        partial void OnOccAccountTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccAccountId
        {
            get
            {
                return _OccAccountId;
            }
            set
            {
                OnOccAccountIdChanging(value);
                ReportPropertyChanging("OccAccountId");
                _OccAccountId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccAccountId");
                OnOccAccountIdChanged();
            }
        }
        private global::System.String _OccAccountId;
        partial void OnOccAccountIdChanging(global::System.String value);
        partial void OnOccAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccCollateralType
        {
            get
            {
                return _OccCollateralType;
            }
            set
            {
                OnOccCollateralTypeChanging(value);
                ReportPropertyChanging("OccCollateralType");
                _OccCollateralType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccCollateralType");
                OnOccCollateralTypeChanged();
            }
        }
        private global::System.String _OccCollateralType;
        partial void OnOccCollateralTypeChanging(global::System.String value);
        partial void OnOccCollateralTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccOptionSymbol
        {
            get
            {
                return _OccOptionSymbol;
            }
            set
            {
                OnOccOptionSymbolChanging(value);
                ReportPropertyChanging("OccOptionSymbol");
                _OccOptionSymbol = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccOptionSymbol");
                OnOccOptionSymbolChanged();
            }
        }
        private global::System.String _OccOptionSymbol;
        partial void OnOccOptionSymbolChanging(global::System.String value);
        partial void OnOccOptionSymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccExpirationYear
        {
            get
            {
                return _OccExpirationYear;
            }
            set
            {
                OnOccExpirationYearChanging(value);
                ReportPropertyChanging("OccExpirationYear");
                _OccExpirationYear = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccExpirationYear");
                OnOccExpirationYearChanged();
            }
        }
        private global::System.String _OccExpirationYear;
        partial void OnOccExpirationYearChanging(global::System.String value);
        partial void OnOccExpirationYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccExpirationMonth
        {
            get
            {
                return _OccExpirationMonth;
            }
            set
            {
                OnOccExpirationMonthChanging(value);
                ReportPropertyChanging("OccExpirationMonth");
                _OccExpirationMonth = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccExpirationMonth");
                OnOccExpirationMonthChanged();
            }
        }
        private global::System.String _OccExpirationMonth;
        partial void OnOccExpirationMonthChanging(global::System.String value);
        partial void OnOccExpirationMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccExpirationDay
        {
            get
            {
                return _OccExpirationDay;
            }
            set
            {
                OnOccExpirationDayChanging(value);
                ReportPropertyChanging("OccExpirationDay");
                _OccExpirationDay = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccExpirationDay");
                OnOccExpirationDayChanged();
            }
        }
        private global::System.String _OccExpirationDay;
        partial void OnOccExpirationDayChanging(global::System.String value);
        partial void OnOccExpirationDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccOptionType
        {
            get
            {
                return _OccOptionType;
            }
            set
            {
                OnOccOptionTypeChanging(value);
                ReportPropertyChanging("OccOptionType");
                _OccOptionType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccOptionType");
                OnOccOptionTypeChanged();
            }
        }
        private global::System.String _OccOptionType;
        partial void OnOccOptionTypeChanging(global::System.String value);
        partial void OnOccOptionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccOptionStrike
        {
            get
            {
                return _OccOptionStrike;
            }
            set
            {
                OnOccOptionStrikeChanging(value);
                ReportPropertyChanging("OccOptionStrike");
                _OccOptionStrike = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccOptionStrike");
                OnOccOptionStrikeChanged();
            }
        }
        private global::System.String _OccOptionStrike;
        partial void OnOccOptionStrikeChanging(global::System.String value);
        partial void OnOccOptionStrikeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccOptionStrikeDecimal
        {
            get
            {
                return _OccOptionStrikeDecimal;
            }
            set
            {
                OnOccOptionStrikeDecimalChanging(value);
                ReportPropertyChanging("OccOptionStrikeDecimal");
                _OccOptionStrikeDecimal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccOptionStrikeDecimal");
                OnOccOptionStrikeDecimalChanged();
            }
        }
        private global::System.String _OccOptionStrikeDecimal;
        partial void OnOccOptionStrikeDecimalChanging(global::System.String value);
        partial void OnOccOptionStrikeDecimalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Blank
        {
            get
            {
                return _Blank;
            }
            set
            {
                OnBlankChanging(value);
                ReportPropertyChanging("Blank");
                _Blank = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Blank");
                OnBlankChanged();
            }
        }
        private global::System.String _Blank;
        partial void OnBlankChanging(global::System.String value);
        partial void OnBlankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CrossReferenceNumber
        {
            get
            {
                return _CrossReferenceNumber;
            }
            set
            {
                OnCrossReferenceNumberChanging(value);
                ReportPropertyChanging("CrossReferenceNumber");
                _CrossReferenceNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CrossReferenceNumber");
                OnCrossReferenceNumberChanged();
            }
        }
        private global::System.String _CrossReferenceNumber;
        partial void OnCrossReferenceNumberChanging(global::System.String value);
        partial void OnCrossReferenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerAccountNumber
        {
            get
            {
                return _CustomerAccountNumber;
            }
            set
            {
                OnCustomerAccountNumberChanging(value);
                ReportPropertyChanging("CustomerAccountNumber");
                _CustomerAccountNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerAccountNumber");
                OnCustomerAccountNumberChanged();
            }
        }
        private global::System.String _CustomerAccountNumber;
        partial void OnCustomerAccountNumberChanging(global::System.String value);
        partial void OnCustomerAccountNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OccFiller
        {
            get
            {
                return _OccFiller;
            }
            set
            {
                OnOccFillerChanging(value);
                ReportPropertyChanging("OccFiller");
                _OccFiller = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OccFiller");
                OnOccFillerChanged();
            }
        }
        private global::System.String _OccFiller;
        partial void OnOccFillerChanging(global::System.String value);
        partial void OnOccFillerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DtccFiller
        {
            get
            {
                return _DtccFiller;
            }
            set
            {
                OnDtccFillerChanging(value);
                ReportPropertyChanging("DtccFiller");
                _DtccFiller = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DtccFiller");
                OnDtccFillerChanged();
            }
        }
        private global::System.String _DtccFiller;
        partial void OnDtccFillerChanging(global::System.String value);
        partial void OnDtccFillerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SourceId
        {
            get
            {
                return _SourceId;
            }
            set
            {
                OnSourceIdChanging(value);
                ReportPropertyChanging("SourceId");
                _SourceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceId");
                OnSourceIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SourceId;
        partial void OnSourceIdChanging(Nullable<global::System.Int32> value);
        partial void OnSourceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceType
        {
            get
            {
                return _SourceType;
            }
            set
            {
                OnSourceTypeChanging(value);
                ReportPropertyChanging("SourceType");
                _SourceType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceType");
                OnSourceTypeChanged();
            }
        }
        private global::System.String _SourceType;
        partial void OnSourceTypeChanging(global::System.String value);
        partial void OnSourceTypeChanged();

        #endregion
    
    }

    #endregion
    
}
